backend:
  name: git-gateway
  repo: thebamp/thebamp.org
  branch: master

media_folder: "site/static/img"
public_folder: "img"

collections:
  - name: "pages"
    label: "Pages"
    files:

      # --- homepage ---
      - file: "site/content/_index.md"
        label: "Homepage"
        name: "homepage"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Intro, name: text, widget: text}
          - label: Metrics
            name: metrics
            widget: list
            summary: "{{fields.number}} {{fields.label}}"
            fields:
              - {label: Image, name: img, widget: image}
              - {label: Number, name: number, widget: string}
              - {label: Label, name: label, widget: string}
          - label: Featured
            name: featured
            widget: list
            fields:
              - {label: Title, name: title, widget: string}
              - {label: Text, name: text, widget: markdown}
              - {label: Image, name: imageUrl, widget: image}
              - {label: "Link Text", name: linkText, widget: string}
              - {label: "Link URL", name: linkUrl, widget: string}
              - {label: Color, name: boxColor, widget: select, options: ["red", "yellow", "blue"]}
          - label: Testimonials
            name: testimonials
            widget: list
            fields:
              - {label: Name, name: name, widget: string}
              - {label: Quote, name: quote, widget: text}
              - {label: Image, name: imageUrl, widget: image}
          - label: Partners
            name: partners
            widget: list
            fields:
              - {label: Image, name: imageUrl, widget: image}
              - {label: "Link URL", name: linkUrl, widget: string, required: false}

      # ---  artwork page ---
      - file: "site/content/artwork/_index.md"
        label: "Artwork Page"
        name: "artwork"
        fields:
          - {label: Title, name: title, widget: string}
          - label: Murals
            name: murals
            widget: list
            fields:
              - {label: ID, name: id, widget: string}
              - {label: Date, name: date, widget: string}
              - {label: Image, name: imageUrl, widget: image}
              - {label: "Lead Artist", name: leadArtist, widget: string}
              - {label: Location, name: location, widget: string}
              - {label: "Thumbnail Image", name: thumbUrl, widget: image}
              - {label: Title, name: title, widget: string}
              - {label: Color, name: boxColor, widget: select, options: ["red", "yellow", "blue"]}
          - label: FAQs (Artwork)
            name: faqs
            widget: list
            fields:
              - {label: Question, name: question, widget: string}
              - {label: Answer, name: answer, widget: markdown}

      # ---  about us page ---
      - file: "site/content/about_us/_index.md"
        label: "About Us Page"
        name: "about_us"
        fields:
          - name: pageHeader
            label: "Page Header (About Us)"
            widget: object
            fields:
            - {label: Title, name: title, widget: string}
            - {label: Caption, name: caption, widget: text}
            - {label: Image, name: imageUrl, widget: image}
            - {label: Color, name: boxColor, widget: select, options: ["red", "yellow", "blue"]}
          - {label: "Mission Statement", name: missionStatement, widget: text}
          - name: teamMembers
            label: "Our Team"
            widget: list
            fields:
              - {label: Name, name: name, widget: string}
              - {label: Role, name: role, widget: string}
              - {label: Image, name: imageUrl, widget: image}
              - {label: Email, name: email, widget: string}
          - label: "Board of Directors"
            name: directors
            widget: list
            fields:
              - {label: Name, name: name, widget: string}
              - {label: Role, name: role, widget: string}
              - {label: Image, name: imageUrl, widget: image}
              - {label: Email, name: email, widget: string}
          - label: "Advisory Committe"
            name: advisors
            widget: list
            fields:
              - {label: Name, name: name, widget: string}
              - {label: Role, name: role, widget: string}
              - {label: Image, name: imageUrl, widget: image}
              - {label: Email, name: email, widget: string}
          - label: Press
            name: press
            widget: list
            fields:
              - {label: Headline, name: headline, widget: string}
              - {label: Date, name: date, widget: string}
              - {label: Color, name: boxColor, widget: select, options: ["red", "yellow", "blue"]}
              - {label: Image, name: imageUrl, widget: image}
              - {label: URL, name: linkUrl, widget: string}
              - {label: Publication, name: publication, widget: string}
              - {label: Text, name: text, widget: text}

      # ---  programs page ---
      - file: "site/content/programs/_index.md"
        label: "Programs Page"
        name: "programs"
        fields:
          - name: pageHeader
            label: "Page Header (Programs)"
            widget: object
            fields:
            - {label: Title, name: title, widget: string}
            - {label: Caption, name: caption, widget: text}
            - {label: Image, name: imageUrl, widget: image}
            - {label: Color, name: boxColor, widget: select, options: ["red", "yellow", "blue"]}
          - name: programs
            label: Programs
            widget: list
            fields:
              - {label: Title, name: title, widget: string}
              - {label: Text, name: text, widget: markdown}
              - {label: Details, name: details, widget: string}
              - {label: Price, name: price, widget: string}
              - {label: Image, name: imageUrl, widget: image}
              - {label: Color, name: boxColor, widget: select, options: ["red", "yellow", "blue"]}
          - name: faqs
            label: FAQs (Programs)
            widget: list
            fields:
              - {label: Question, name: question, widget: string}
              - {label: Answer, name: answer, widget: markdown}
          - name: photos
            label: "Photos"
            widget: list
            fields:
              - {label: Image, name: imageUrl, widget: image}

      # ---  events page ---
      - file: "site/content/events/_index.md"
        label: "Events Page"
        name: "events"
        fields:
          - name: events
            label: Events
            widget: list
            fields:
              - {label: Title, name: title, widget: string}
              - {label: Description, name: description, widget: markdown}
              - {label: Date, name: date, widget: string}
              - {label: Image, name: imageUrl, widget: image}
              - {label: Color, name: boxColor, widget: select, options: ["red", "yellow", "blue"]}
              - {label: "Link URL", name: linkUrl, widget: string}
          - name: photos
            label: "Photos"
            widget: list
            fields:
              - {label: Image, name: imageUrl, widget: image}

      # ---  services page ---
      - file: "site/content/services/_index.md"
        label: "Services Page"
        name: "services"
        fields:
          - name: pageHeader
            label: "Page Header (Services)"
            widget: object
            fields:
            - {label: Title, name: title, widget: string}
            - {label: Caption, name: caption, widget: text}
            - {label: Image, name: imageUrl, widget: image}
            - {label: Color, name: boxColor, widget: select, options: ["red", "yellow", "blue"]}
          - name: cards
            label: Info Cards
            widget: list
            fields:
              - {label: Title, name: title, widget: string}
              - {label: Image, name: imageUrl, widget: image}
              - {label: Description, name: description, widget: markdown}
              - {label: "Action URL", name: linkUrl, widget: string}
              - {label: "Action Text", name: linktext, widget: string}
              - {label: Color, name: boxColor, widget: select, options: ["red", "yellow", "blue"]}

      # ---  get involved page ---
      - file: "site/content/get_involved/_index.md"
        label: "Get Involved Page"
        name: "get_involved"
        fields:
          - name: pageHeader
            label: "Page Header (Get Involved)"
            widget: object
            fields:
            - {label: Title, name: title, widget: string}
            - {label: Caption, name: caption, widget: text}
            - {label: Image, name: imageUrl, widget: image}
            - {label: Color, name: boxColor, widget: select, options: ["red", "yellow", "blue"]}
          - name: cards
            label: Info Cards
            widget: list
            fields:
              - {label: Title, name: title, widget: string}
              - {label: Image, name: imageUrl, widget: image}
              - {label: Description, name: description, widget: markdown}
              - {label: "Action URL", name: linkUrl, widget: string}
              - {label: "Action Text", name: linktext, widget: string}
              - {label: Color, name: boxColor, widget: select, options: ["red", "yellow", "blue"]}
          - label: FAQs (Get Involved)
            name: faqs
            widget: list
            fields:
              - {label: Question, name: question, widget: string}
              - {label: Answer, name: answer, widget: markdown}
